apiVersion: v1
kind: Service
metadata: 
  name: web-app
  annotations: 
    service.beta.kubernetes.azure-load-balancer-internal: "true"
spec: 
  type: LoadBalancer
  ports: 
  - port: 80
  seletor: 
    app: web-app